<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ITGS-Shivanee-Sapte" failures="1" tests="5" name="RetryMultipleFailedTestCases" time="0.827" errors="0" timestamp="2025-08-18T12:28:55 IST">
  <testcase classname="AnalyzerTest.TestCase1" name="test1" time="0.13">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="AnalyzerTest.TestCase1" name="test1" time="0.008">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="AnalyzerTest.TestCase1" name="test1" time="0.008">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="AnalyzerTest.TestCase1" name="test1" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at AnalyzerTest.TestCase1.test1(TestCase1.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="AnalyzerTest.TestCase1" name="test2" time="0.007"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
